name: Release App Builds

on:
  push:
    branches:
    - main

jobs:
    Desktop:
        strategy:
            fail-fast: false
            matrix:
                settings:
                    - platform: 'macos-latest'
                      args: '--target universal-apple-darwin'
                    - platform: 'ubuntu-latest'
                      # args: ''
                    - platform: 'windows-latest'
                      args: '--target x86_64-pc-windows-msvc'

        runs-on: ${{ matrix.settings.platform }}

        steps:
            - uses: actions/checkout@v2
            - uses: oven-sh/setup-bun@v1

            - name: Install dependencies
              run: bun install

            - name: Build web and desktop apps
              run: bun run tauri build

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: us-east-1
            
            - name: Copy to S3
              run: aws s3 sync ./dist/. s3://aerodis.space/${{ matrix.settings.platform }}
    